general:
steps:
 gctsDeploy:
 host: "https://tst.opensap.consarea.com:44300"
 client: "100"
 abapCredentialsId: "BBJAOIWB_credentials"
 repository: "ibarbaric-opensap_gcts1_customizing"
 remoteRepositoryURL: "https://github.com/ibarbaric/openSAP_gcts1_workbench"
 role: "SOURCE"
 vSID: "BBJ"
 verbose: true
 type: "GITHUB"
 rollback: false
